<a href="https://colab.research.google.com/github/sampritich/samplerepo/blob/master/basics_of_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v1.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow_core/_api/v1/version/__init__.py'>


In [0]:
hello = tf.constant("Hi")
type(hello)


tensorflow.python.framework.ops.Tensor

In [0]:
print(hello) # by printing hello you will not able to fetch the data in tensorflow 

Tensor("Const_1:0", shape=(), dtype=string)


In [0]:
sess = tf.Session()  # to do any kind of operation in tensorflow you need to use session object
print(sess.run(hello)) # output b term for bytes
  
   

b'Hi'


In [0]:
#addition perform

a = tf.constant(10)

b = tf.constant(20)

sess= tf.Session()

print(sess.run(a+b))

30


In [0]:
# Tensor is n dimentionaal array


In [0]:
fill_mat = tf.fill((4,4),10)
sess = tf.Session() 

print(sess.run(fill_mat)) # It will create a array of 4*4 with value = 10

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [0]:
Zero_mat= tf.zeros((4*4))

sess = tf.Session() 

print(sess.run(Zero_mat)) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [0]:
one_mat = tf.ones(4*4)
sess = tf.Session() 

print(sess.run(one_mat)) 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [0]:
sess=tf.InteractiveSession()

In [0]:
fun = [fill_mat,Zero_mat,one_mat]

for i in fun:
  print(sess.run(i))
  print('\n')

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]




In [0]:
arr= tf.constant([[1,2],[2,3]])
arr.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [0]:
sess=tf.Session()

print(sess.run(arr))

[[1 2]
 [2 3]]


In [0]:
arr1= tf.constant([[1],[100]])
arr1.get_shape()

result=tf.matmul(arr,arr1)



sess=tf.Session()

print(sess.run(result))


[[201]
 [302]]


tensorflow graoh has two main object

1.   variable
2.   placeholder



**Variable:** 

1.   It can hold the weight and biases throughout the session
2.   variable needs to be initialized


**Placeholders:**


1.   They are initially empty and used to feed in the actual training
2.   you need to declare them with datatype and shape





In [0]:
import tensorflow as tf


var1 = tf.Variable(3)

**To execute tensorflow variable you need to initialize global_variable_initializer**

In [7]:
sess= tf.Session()
sess.run(var1)

FailedPreconditionError: ignored

In [10]:
init = tf.global_variables_initializer()

sess.run(init)


sess.run(var1)

3

In [0]:
p1 = tf.placeholder(tf.float32)