<a href="https://colab.research.google.com/github/sampritich/samplerepo/blob/master/simple_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import numpy as np


In [0]:
a= tf.placeholder(tf.float32)


b= tf.placeholder(tf.float32)



random_a = np.random.uniform(0,100,(5,5))

random_b = np.random.uniform(0,100,(5,5))



In [0]:
add = a+b


mul = a*b

In [16]:
sess= tf.Session()

result=sess.run(add,feed_dict={a:random_a,b:random_b})
print(result)

[[ 67.172195 129.11264  108.67355   14.593181  20.939785]
 [159.21497   98.60312   46.32036  169.13158  177.66977 ]
 [ 62.904793 157.05739   82.55745   17.416138 125.61427 ]
 [123.529305  56.95148  166.51627  163.19727  130.04312 ]
 [ 53.09423  166.58612   38.336304  75.16363  111.462425]]


In [0]:
n_features = 10

n_dense_neurons=3

In [0]:
x=tf.placeholder(tf.float32,(None,n_features))


w= tf.Variable(tf.random_normal([n_features,n_dense_neurons]))


b= tf.Variable(tf.ones([n_dense_neurons]))

In [0]:
xW=tf.matmul(x,w)


z=tf.add(xW,b)

In [0]:
a=tf.nn.relu(z)

In [29]:
init = tf.global_variables_initializer()

sess = tf.Session()

sess.run(init)


layer_out=sess.run(a,feed_dict={x:np.random.random([1,n_features])})

print(layer_out)

[[2.0415573 0.        4.3385577]]
